# Generated by Django 5.1 on 2024-10-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.CharField(max_length=30),
        ),
    ]
