# Generated by Django 5.1 on 2024-10-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_alter_auto_modelo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='año',
            new_name='anio',
        ),
    ]
