# Generated by Django 5.1 on 2024-10-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_alter_auto_precio_por_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
