# Generated by Django 5.1 on 2024-10-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_alter_auto_precio_por_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='disponible',
            field=models.IntegerField(default=0),
        ),
    ]
