# Generated by Django 5.1 on 2024-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_alter_auto_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField()),
                ('apellidos', models.CharField()),
                ('Direcion', models.CharField()),
                ('telefono', models.CharField()),
                ('No_licencia', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField()),
                ('clientes', models.CharField()),
                ('salida', models.CharField()),
                ('entradas', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='matricula',
            field=models.CharField(default='0000', max_length=8),
        ),
    ]
