# Generated by Django 5.1 on 2024-10-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_alter_auto_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('Direcion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('No_licencia', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('clientes', models.ForeignKey(on_delete=models.CASCADE, to='carros.Clientes')),
                ('entradas', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='matricula',
            field=models.CharField(default='0000', max_length=8),
        ),
    ]

