# Generated by Django 5.1 on 2024-10-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_clientes_reservaciones_auto_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='estado',
            field=models.IntegerField(default='3', max_length=5),
        ),
    ]
