# Generated by Django 5.1 on 2024-10-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_auto_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='estado',
            field=models.CharField(default='3', max_length=5),
        ),
    ]
