# Generated by Django 5.1 on 2024-10-22 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0010_rename_direcion_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='estado',
            field=models.CharField(default='3', max_length=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(default='0000', max_length=10),
        ),
    ]
