# Generated by Django 5.1 on 2024-10-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0011_alter_auto_estado_alter_clientes_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='matricula',
            field=models.CharField(default='0000', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='no_licencia',
            field=models.CharField(default='0000', max_length=10, unique=True),
        ),
    ]
