# Generated by Django 5.1 on 2024-11-21 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0012_alter_auto_matricula_alter_clientes_no_licencia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reservaciones',
            new_name='reservacion',
        ),
    ]
