# Generated by Django 5.1.2 on 2024-12-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0014_alter_clientes_apellidos_alter_clientes_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservacion',
            name='entrada',
        ),
    ]
