# Generated by Django 5.1.2 on 2024-12-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0015_remove_reservacion_salidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservacion',
            name='entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
